github_url = "https://github.com/"

webdriver_endpoint = 'http://localhost:4444/wd/hub'

[locators]
    [locators.search.q]
        by = 'XPATH'
        selector = '//input[@name="q"]'
    [locators.advanced.search.page]
        by = 'ID'
        selector = 'search-title'
    [locators.search.advanced]
        by = 'LINK_TEXT'
        selector = 'Advanced search'
    [locators.search.user.followers]
        by = 'ID'
        selector = 'search_followers'
        value = '>50'
    [locators.search.user.language]
        by = 'ID'
        selector = "search_user_language"
    [locators.search.user.language.option]
        by = 'XPATH'
        selector = "//option[@value='%s']"
        value = 'JavaScript'
    [locators.search.issues]
        by = 'ID'
        selector = "search_state"
    [locators.search.issues.state]
        by = "XPATH"
        selector = "//option[@value='%s']"
        value = "closed"
    [locators.search.stars]
        by = "ID"
        selector = "search_stars"
        value = ">45"
    [locators.search.license]
        by = "ID"
        selector = "search_license"
    [locators.search.license.option]
        by = "XPATH"
        selector = "//option[@value='%s']"
        value = "bsl-1.0"
    [locators.search.button]
        by = "XPATH"
        selector = "//button[@type='submit']"